AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'db/migrate/**'
    - 'Gemfile'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'log/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 35

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/**/*'
